language: python
python:
  - "3.6"
env:
  - DJANGO_SETTINGS_MODULE=killington.settings.test
services:
  - postgresql
install:
  - pip install -r requirements-dev.txt
before_script:
  - make dropdb createdb migrate
script:
  - piprot
  - make test