# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 03:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default=12345, max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numbers allowed.')], verbose_name='ZIP code'),
            preserve_default=False,
        ),
    ]
