# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20170218_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='starts_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
