# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20170219_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
