# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20170224_0211'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='processed',
        ),
        migrations.AlterField(
            model_name='lottery',
            name='entered_users',
            field=models.ManyToManyField(blank=True, related_name='entered_lotteries', to=settings.AUTH_USER_MODEL),
        ),
    ]
