# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:29
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20170225_2020'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
