# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_ses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_floods', to=settings.AUTH_USER_MODEL)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Lottery')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_floods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ses',
            options={'verbose_name': 'SES', 'verbose_name_plural': 'SES Set'},
        ),
    ]
