# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_auto_20170501_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ses',
            options={'ordering': ('id',), 'verbose_name': 'SES', 'verbose_name_plural': 'SES Set'},
        ),
        migrations.AddField(
            model_name='flood',
            name='entered_ses_set',
            field=models.ManyToManyField(to='shows.SES'),
        ),
    ]
