# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_auto_20170502_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='flood',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flood',
            name='entered_ses_set',
            field=models.ManyToManyField(blank=True, to='shows.SES'),
        ),
    ]
